![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [1]:
# We've loaded your first package for you! You can add as many cells as you need.
import numpy as np
import pandas as pd
import datetime as dt

In [2]:
# Create variables for each file type and file name
csv_file = 'data/airbnb_price.csv'
xls_file = 'data/airbnb_room_type.xlsx'
tsv_file = 'data/airbnb_last_review.tsv'

# Read each file and convert to DataFrame
df_price = pd.read_csv(csv_file)
df_room_type = pd.read_excel(xls_file)
df_last_review = pd.read_csv(tsv_file, delimiter='\t')

# Analyse DataFrames info and columns
df_list = [df_price, df_room_type, df_last_review]
[print(df.info()) for df in df_list]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   price        25209 non-null  object
 2   nbhood_full  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   description  25199 non-null  object
 2   room_type    25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25209 entries, 0 to 25208
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   listing_id   25209 non-null  int64
 1   host_name    25201 non-null  object
 2   last_review  25209 non-null  object
dtypes: int64(1), object(2)
memory usage: 591.0+ KB
None

[None, None, None]

In [3]:
# Explore earliest and most recent review
# Explore last_review DataFrame
review_date = df_last_review['last_review']

# Convert column to date
review_date = pd.to_datetime(review_date).dt.date

# Assign earliest and most recent dates to variables
earliest = review_date.min()
latest = review_date.max()

print(earliest, latest)
print(review_date.sort_values())

2019-01-01 2019-07-09
12007    2019-01-01
10430    2019-01-01
14845    2019-01-01
7203     2019-01-01
17123    2019-01-01
            ...
23952    2019-07-08
9595     2019-07-08
9505     2019-07-08
17563    2019-07-08
58       2019-07-09
Name: last_review, Length: 25209, dtype: object

In [4]:
# Explore private rooms count
# Explore room_type DataFrame
print(df_room_type.head())

# Analyze room_type column
room_type = df_room_type['room_type']
print(room_type.unique())

# Uniform room_type column
room_type = room_type.str.lower()
print(room_type.unique())

# Extract count of private rooms
pvt_rooms = room_type[room_type == 'private room'].count()
print(pvt_rooms)
print(room_type.value_counts())

   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt
['Entire home/apt' 'private room' 'Private room' 'entire home/apt'
 'PRIVATE ROOM' 'shared room' 'ENTIRE HOME/APT' 'Shared room'
 'SHARED ROOM']
['entire home/apt' 'private room' 'shared room']
11356
entire home/apt    13266
private room       11356
shared room          587
Name: room_type, dtype: int64

In [5]:
# Explore average listing price
# Explore price DataFrame
print(df_price.head())

# Extract price column
price = df_price['price']

# Clean price column and convert to int column
price = price.str.replace(' dollars', '')
price = price.str.strip()
price = price.astype(int)
print(price)

# Calculate average price
avg_price = round(price.mean(), 2)
print(avg_price)

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown
0        225
1         89
2        200
3         79
4        150
        ...
25204    129
25205     45
25206    235
25207    100
25208     30
Name: price, Length: 25209, dtype: int64
141.78

In [6]:
# Create review_dates DataFrame
col_labels = ['first_reviewed', 'last_reviewed', 'nb_private_rooms', 'avg_price']
df_values = [[earliest], [latest], [pvt_rooms], [avg_price]]
dict_review_dates = dict(zip(col_labels, df_values))
review_dates = pd.DataFrame(dict_review_dates)
print(review_dates)

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78